In [ ]:
%pip install requests pandas

# Cryptocurrencies

In [7]:
all_records=[]
import requests
url="https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
response=requests.get(url)
response.status_code

200

In [8]:
if response.status_code==200:
    data=response.json()
    all_records.extend(data)
all_records

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 6113115,
  'market_cap': 122071170909890,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 122071170909890,
  'total_volume': 4942894684860,
  'high_24h': 6203260,
  'low_24h': 5981247,
  'price_change_24h': -41374.53554757126,
  'price_change_percentage_24h': -0.67227,
  'market_cap_change_24h': -1324843788784.875,
  'market_cap_change_percentage_24h': -1.07365,
  'circulating_supply': 19987943.0,
  'total_supply': 19987943.0,
  'max_supply': 21000000.0,
  'ath': 11187013,
  'ath_change_percentage': -45.35526,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 3993.42,
  'atl_change_percentage': 152979.70943,
  'atl_date': '2013-07-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:00.514Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 178500,
  'market_cap': 21498509917459,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 21498509917459,
  'total_volume': 2217479903295,
  'high_24h': 181389,
  'low_24h': 173470,
  'price_change_24h': -2584.722176509036,
  'price_change_percentage_24h': -1.42736,
  'market_cap_change_24h': -427424491748.90625,
  'market_cap_change_percentage_24h': -1.9494,
  'circulating_supply': 120692542.2815806,
  'total_supply': 120692542.2815806,
  'max_supply': None,
  'ath': 431946,
  'ath_change_percentage': -58.67541,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 28.13,
  'atl_change_percentage': 634425.09497,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 38.03971153615691,
   'currency': 'btc',
   'percentage': 3803.971153615691},
  'last_updated': '2026-02-12T04:16:00.872Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 90.46,
  'market_cap': 16640443292479,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 17134801095353,
  'total_volume': 7806862742638,
  'high_24h': 90.77,
  'low_24h': 90.37,
  'price_change_24h': 0.00378925,
  'price_change_percentage_24h': 0.00419,
  'market_cap_change_24h': -37730143709.83203,
  'market_cap_change_percentage_24h': -0.22622,
  'circulating_supply': 184021084709.7995,
  'total_supply': 189488021949.4362,
  'max_supply': None,
  'ath': 105.52,
  'ath_change_percentage': -14.23517,
  'ath_date': '2025-01-25T16:51:57.989Z',
  'atl': 36.86,
  'atl_change_percentage': 145.52081,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.939Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 55861,
  'market_cap': 7614776553122,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 7614776553122,
  'total_volume': 144933998233,
  'high_24h': 55959,
  'low_24h': 53277,
  'price_change_24h': 67.88,
  'price_change_percentage_24h': 0.12167,
  'market_cap_change_24h': -9581604833.475586,
  'market_cap_change_percentage_24h': -0.12567,
  'circulating_supply': 136359446.92,
  'total_supply': 136359446.92,
  'max_supply': 200000000.0,
  'ath': 121422,
  'ath_change_percentage': -53.99461,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 2.58,
  'atl_change_percentage': 2161073.58445,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:00.574Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 124.65,
  'market_cap': 7582873135614,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 12446034985477,
  'total_volume': 299852143076,
  'high_24h': 127.0,
  'low_24h': 122.09,
  'price_change_24h': -2.345520955241497,
  'price_change_percentage_24h': -1.84686,
  'market_cap_change_24h': -171996450240.18555,
  'market_cap_change_percentage_24h': -2.21792,
  'circulating_supply': 60917315351.0,
  'total_supply': 99985721048.0,
  'max_supply': 100000000000.0,
  'ath': 313.99,
  'ath_change_percentage': -60.29937,
  'ath_date': '2025-07-21T15:02:00.541Z',
  'atl': 0.159343,
  'atl_change_percentage': 78130.54313,
  'atl_date': '2013-08-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.768Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 90.5,
  'market_cap': 6632385684338,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 6633385245395,
  'total_volume': 525744684430,
  'high_24h': 90.8,
  'low_24h': 90.42,
  'price_change_24h': 0.01466927,
  'price_change_percentage_24h': 0.01621,
  'market_cap_change_24h': 459758931,
  'market_cap_change_percentage_24h': 0.00693,
  'circulating_supply': 73312539559.32837,
  'total_supply': 73323588428.17172,
  'max_supply': None,
  'ath': 1327.87,
  'ath_change_percentage': -93.18233,
  'ath_date': '2025-01-23T04:45:51.184Z',
  'atl': 65.31,
  'atl_change_percentage': 38.62018,
  'atl_date': '2021-05-19T13:14:05.611Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.857Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 7308.84,
  'market_cap': 4145950976085,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 4528680159133,
  'total_volume': 409529476338,
  'high_24h': 7508.19,
  'low_24h': 7106.6,
  'price_change_24h': -199.34722861017053,
  'price_change_percentage_24h': -2.65506,
  'market_cap_change_24h': -136234971895.33887,
  'market_cap_change_percentage_24h': -3.18144,
  'circulating_supply': 567838206.9379966,
  'total_supply': 620257604.634298,
  'max_supply': None,
  'ath': 25396,
  'ath_change_percentage': -71.22086,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 38.03,
  'atl_change_percentage': 19120.79484,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.650Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 25.22,
  'market_cap': 2385901622381,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 2385919872441,
  'total_volume': 59067070733,
  'high_24h': 25.3,
  'low_24h': 24.83,
  'price_change_24h': 0.219812,
  'price_change_percentage_24h': 0.87929,
  'market_cap_change_24h': 16794793781,
  'market_cap_change_percentage_24h': 0.70891,
  'circulating_supply': 94721007851.9235,
  'total_supply': 94721732384.7712,
  'max_supply': None,
  'ath': 36.53,
  'ath_change_percentage': -30.95615,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.117589,
  'atl_change_percentage': 21346.33316,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 145.64231900719585,
   'currency': 'usd',
   'percentage': 14564.231900719584},
  'last_updated': '2026-02-12T04:16:04.489Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 94.55,
  'market_cap': 1426133796584,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 1426133796584,
  'total_volume': 4076403880,
  'high_24h': 94.79,
  'low_24h': 92.87,
  'price_change_24h': 1.15,
  'price_change_percentage_24h': 1.2305,
  'market_cap_change_24h': 18977184917,
  'market_cap_change_percentage_24h': 1.34862,
  'circulating_supply': 15088846748.267,
  'total_supply': 15088846748.267,
  'max_supply': None,
  'ath': 120.96,
  'ath_change_percentage': -21.84998,
  'ath_date': '2025-10-28T06:00:43.161Z',
  'atl': 13.78,
  'atl_change_percentage': 585.77337,
  'atl_date': '2025-10-31T14:57:19.271Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.196Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 8.33,
  'market_cap': 1405111129600,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 1405402616043,
  'total_volume': 101032027769,
  'high_24h': 8.4,
  'low_24h': 8.02,
  'price_change_24h': -0.07010488475473231,
  'price_change_percentage_24h': -0.83435,
  'market_cap_change_24h': -15437877011.09082,
  'market_cap_change_percentage_24h': -1.08675,
  'circulating_supply': 168669383126.5791,
  'total_supply': 168704373126.579,
  'max_supply': None,
  'ath': 53.62,
  'ath_change_percentage': -84.45984,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 0.00552883,
  'atl_change_percentage': 150605.92233,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.579Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 4591.21,
  'market_cap': 982531224454,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1472119321679,
  'total_volume': 10929538898,
  'high_24h': 4647.34,
  'low_24h': 4502.54,
  'price_change_24h': -52.89752224252152,
  'price_change_percentage_24h': -1.13902,
  'market_cap_change_24h': -10914577413.323242,
  'market_cap_change_percentage_24h': -1.09866,
  'circulating_supply': 213729819.0,
  'total_supply': 320229819.0,
  'max_supply': 400000000.0,
  'ath': 5758.63,
  'ath_change_percentage': -20.15135,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 245.71,
  'atl_change_percentage': 1771.40694,
  'atl_date': '2022-09-21T23:38:03.675Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.274Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 46591,
  'market_cap': 930952639483,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 930965298699,
  'total_volume': 31776290711,
  'high_24h': 47453,
  'low_24h': 46132,
  'price_change_24h': -554.2096908578824,
  'price_change_percentage_24h': -1.17553,
  'market_cap_change_24h': -12182284394.346191,
  'market_cap_change_percentage_24h': -1.29168,
  'circulating_supply': 19993556.14665078,
  'total_supply': 19993828.02165078,
  'max_supply': 21000000.0,
  'ath': 242198,
  'ath_change_percentage': -80.76314,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 5536.54,
  'atl_change_percentage': 741.52361,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.517Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 90.45,
  'market_cap': 873200375718,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 873200375718,
  'total_volume': 8661551501,
  'high_24h': 90.8,
  'low_24h': 90.37,
  'price_change_24h': -0.046008065002538956,
  'price_change_percentage_24h': -0.05084,
  'market_cap_change_24h': 7679344704,
  'market_cap_change_percentage_24h': 0.88725,
  'circulating_supply': 9659153059.41872,
  'total_supply': 9659153059.41872,
  'max_supply': None,
  'ath': 92.23,
  'ath_change_percentage': -1.97179,
  'ath_date': '2026-01-29T16:30:24.390Z',
  'atl': 79.67,
  'atl_change_percentage': 13.48171,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.333Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 23.43,
  'market_cap': 861542860952,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 1053679975958,
  'total_volume': 37590258145,
  'high_24h': 23.79,
  'low_24h': 22.81,
  'price_change_24h': -0.22468547646870718,
  'price_change_percentage_24h': -0.94966,
  'market_cap_change_24h': -12340330235.120117,
  'market_cap_change_percentage_24h': -1.41213,
  'circulating_supply': 36794311012.29324,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 225.26,
  'ath_change_percentage': -89.5966,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 1.38,
  'atl_change_percentage': 1603.84239,
  'atl_date': '2017-11-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.821Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 762.8,
  'market_cap': 702427295602,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 751108798167,
  'total_volume': 158057157,
  'high_24h': 768.23,
  'low_24h': 739.45,
  'price_change_24h': 6.71,
  'price_change_percentage_24h': 0.88745,
  'market_cap_change_24h': 4522681310,
  'market_cap_change_percentage_24h': 0.64804,
  'circulating_supply': 921383322.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 888.26,
  'ath_change_percentage': -14.09385,
  'ath_date': '2025-12-01T06:16:28.002Z',
  'atl': 56.97,
  'atl_change_percentage': 1239.33647,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.277Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 2773.14,
  'market_cap': 659946095455,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 2663960175669,
  'total_volume': 30199566842,
  'high_24h': 2795.71,
  'low_24h': 2579.9,
  'price_change_24h': 178.37,
  'price_change_percentage_24h': 6.87425,
  'market_cap_change_24h': 38860940571,
  'market_cap_change_percentage_24h': 6.25694,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 5213.52,
  'ath_change_percentage': -46.80877,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 321.88,
  'atl_change_percentage': 761.54569,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.297Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 31870,
  'market_cap': 583612518850,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 583612518850,
  'total_volume': 7932037724,
  'high_24h': 31948,
  'low_24h': 30245,
  'price_change_24h': 808.56,
  'price_change_percentage_24h': 2.60306,
  'market_cap_change_24h': 9322844442,
  'market_cap_change_percentage_24h': 1.62337,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 72026,
  'ath_change_percentage': -55.75147,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 13.57,
  'atl_change_percentage': 234744.03852,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.355Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 90.4,
  'market_cap': 575672477768,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 575672477768,
  'total_volume': 14754076713,
  'high_24h': 90.71,
  'low_24h': 90.29,
  'price_change_24h': 0.00222289,
  'price_change_percentage_24h': 0.00246,
  'market_cap_change_24h': -5597454563.898071,
  'market_cap_change_percentage_24h': -0.96297,
  'circulating_supply': 6371643821.691264,
  'total_supply': 6371643821.691264,
  'max_supply': None,
  'ath': 92.91,
  'ath_change_percentage': -2.7458,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 78.05,
  'atl_change_percentage': 15.7817,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.410Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 15.1,
  'market_cap': 566295660835,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 566295660835,
  'total_volume': 1263121076,
  'high_24h': 15.3,
  'low_24h': 14.71,
  'price_change_24h': 0.095684,
  'price_change_percentage_24h': 0.63762,
  'market_cap_change_24h': -540109826.439209,
  'market_cap_change_percentage_24h': -0.09529,
  'circulating_supply': 37730423662.41153,
  'total_supply': 37730423662.41153,
  'max_supply': None,
  'ath': 17.72,
  'ath_change_percentage': -15.39275,
  'ath_date': '2026-01-31T16:41:41.560Z',
  'atl': 5.31,
  'atl_change_percentage': 182.45525,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-02-12T04:16:04.370Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 762.49,
  'market_cap': 539684475036,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 762158589967,
  'total_volume': 37598199071,
  'high_24h': 772.19,
  'low_24h': 740.26,
  'price_change_24h': -7.473779857015984,
  'price_change_percentage_24h': -0.97067,
  'market_cap_change_24h': -7783866335.832336,
  'market_cap_change_percentage_24h': -1.42179,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 3862.15,
  'ath_change_percentage': -80.25742,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 9.55,
  'atl_change_percentage': 7886.96168,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.722Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 90.43,
  'market_cap': 486430640010,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 486430640010,
  'total_volume': 220824195703,
  'high_24h': 90.82,
  'low_24h': 90.34,
  'price_change_24h': -0.0605849002316603,
  'price_change_percentage_24h': -0.06695,
  'market_cap_change_24h': -406818584.0609131,
  'market_cap_change_percentage_24h': -0.08356,
  'circulating_supply': 5380664311.030412,
  'total_supply': 5380664311.030412,
  'max_supply': None,
  'ath': 92.17,
  'ath_change_percentage': -1.88123,
  'ath_date': '2026-01-28T15:56:38.616Z',
  'atl': 83.75,
  'atl_change_percentage': 7.98155,
  'atl_date': '2025-05-02T03:46:49.689Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.826Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 14.17,
  'market_cap': 463234670464,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 707754434460,
  'total_volume': 9151336836,
  'high_24h': 14.26,
  'low_24h': 13.7,
  'price_change_24h': -0.021558417652073558,
  'price_change_percentage_24h': -0.15193,
  'market_cap_change_24h': -2336903897.3499146,
  'market_cap_change_percentage_24h': -0.50194,
  'circulating_supply': 32726833124.45822,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 58.01,
  'ath_change_percentage': -75.5751,
  'ath_date': '2021-05-16T09:48:45.220Z',
  'atl': 0.02966141,
  'atl_change_percentage': 47666.39853,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-12T04:15:52.675Z'},
 {'id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'image': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  'current_price': 90.52,
  'market_cap': 378848861601,
  'market_cap_rank': 23,
  'fully_diluted_valuation': 378848861601,

In [9]:
len(all_records)

250

In [10]:
for i in all_records:
    print(i)

{'id': 'bitcoin', 'symbol': 'btc', 'name': 'Bitcoin', 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400', 'current_price': 6113115, 'market_cap': 122071170909890, 'market_cap_rank': 1, 'fully_diluted_valuation': 122071170909890, 'total_volume': 4942894684860, 'high_24h': 6203260, 'low_24h': 5981247, 'price_change_24h': -41374.53554757126, 'price_change_percentage_24h': -0.67227, 'market_cap_change_24h': -1324843788784.875, 'market_cap_change_percentage_24h': -1.07365, 'circulating_supply': 19987943.0, 'total_supply': 19987943.0, 'max_supply': 21000000.0, 'ath': 11187013, 'ath_change_percentage': -45.35526, 'ath_date': '2025-10-06T18:57:42.558Z', 'atl': 3993.42, 'atl_change_percentage': 152979.70943, 'atl_date': '2013-07-05T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:16:00.514Z'}
{'id': 'ethereum', 'symbol': 'eth', 'name': 'Ethereum', 'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628', 'current_price': 178500, 'market_cap': 21498509917459, 'market_cap_rank': 2, 'fully_diluted_valuation': 21498509917459, 'total_volume': 2217479903295, 'high_24h': 181389, 'low_24h': 173470, 'price_change_24h': -2584.722176509036, 'price_change_percentage_24h': -1.42736, 'market_cap_change_24h': -427424491748.90625, 'market_cap_change_percentage_24h': -1.9494, 'circulating_supply': 120692542.2815806, 'total_supply': 120692542.2815806, 'max_supply': None, 'ath': 431946, 'ath_change_percentage': -58.67541, 'ath_date': '2025-08-24T19:21:03.333Z', 'atl': 28.13, 'atl_change_percentage': 634425.09497, 'atl_date': '2015-10-20T00:00:00.000Z', 'roi': {'times': 38.03971153615691, 'currency': 'btc', 'percentage': 3803.971153615691}, 'last_updated': '2026-02-12T04:16:00.872Z'}
{'id': 'tether', 'symbol': 'usdt', 'name': 'Tether', 'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661', 'current_price': 90.46, 'market_cap': 16640443292479, 'market_cap_rank': 3, 'fully_diluted_valuation': 17134801095353, 'total_volume': 7806862742638, 'high_24h': 90.77, 'low_24h': 90.37, 'price_change_24h': 0.00378925, 'price_change_percentage_24h': 0.00419, 'market_cap_change_24h': -37730143709.83203, 'market_cap_change_percentage_24h': -0.22622, 'circulating_supply': 184021084709.7995, 'total_supply': 189488021949.4362, 'max_supply': None, 'ath': 105.52, 'ath_change_percentage': -14.23517, 'ath_date': '2025-01-25T16:51:57.989Z', 'atl': 36.86, 'atl_change_percentage': 145.52081, 'atl_date': '2015-03-02T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.939Z'}
{'id': 'binancecoin', 'symbol': 'bnb', 'name': 'BNB', 'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970', 'current_price': 55861, 'market_cap': 7614776553122, 'market_cap_rank': 4, 'fully_diluted_valuation': 7614776553122, 'total_volume': 144933998233, 'high_24h': 55959, 'low_24h': 53277, 'price_change_24h': 67.88, 'price_change_percentage_24h': 0.12167, 'market_cap_change_24h': -9581604833.475586, 'market_cap_change_percentage_24h': -0.12567, 'circulating_supply': 136359446.92, 'total_supply': 136359446.92, 'max_supply': 200000000.0, 'ath': 121422, 'ath_change_percentage': -53.99461, 'ath_date': '2025-10-13T08:41:24.131Z', 'atl': 2.58, 'atl_change_percentage': 2161073.58445, 'atl_date': '2017-10-19T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:16:00.574Z'}
{'id': 'ripple', 'symbol': 'xrp', 'name': 'XRP', 'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442', 'current_price': 124.65, 'market_cap': 7582873135614, 'market_cap_rank': 5, 'fully_diluted_valuation': 12446034985477, 'total_volume': 299852143076, 'high_24h': 127.0, 'low_24h': 122.09, 'price_change_24h': -2.345520955241497, 'price_change_percentage_24h': -1.84686, 'market_cap_change_24h': -171996450240.18555, 'market_cap_change_percentage_24h': -2.21792, 'circulating_supply': 60917315351.0, 'total_supply': 99985721048.0, 'max_supply': 100000000000.0, 'ath': 313.99, 'ath_change_percentage': -60.29937, 'ath_date': '2025-07-21T15:02:00.541Z', 'atl': 0.159343, 'atl_change_percentage': 78130.54313, 'atl_date': '2013-08-16T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.768Z'}
{'id': 'usd-coin', 'symbol': 'usdc', 'name': 'USDC', 'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602', 'current_price': 90.5, 'market_cap': 6632385684338, 'market_cap_rank': 6, 'fully_diluted_valuation': 6633385245395, 'total_volume': 525744684430, 'high_24h': 90.8, 'low_24h': 90.42, 'price_change_24h': 0.01466927, 'price_change_percentage_24h': 0.01621, 'market_cap_change_24h': 459758931, 'market_cap_change_percentage_24h': 0.00693, 'circulating_supply': 73312539559.32837, 'total_supply': 73323588428.17172, 'max_supply': None, 'ath': 1327.87, 'ath_change_percentage': -93.18233, 'ath_date': '2025-01-23T04:45:51.184Z', 'atl': 65.31, 'atl_change_percentage': 38.62018, 'atl_date': '2021-05-19T13:14:05.611Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.857Z'}
{'id': 'solana', 'symbol': 'sol', 'name': 'Solana', 'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756', 'current_price': 7308.84, 'market_cap': 4145950976085, 'market_cap_rank': 7, 'fully_diluted_valuation': 4528680159133, 'total_volume': 409529476338, 'high_24h': 7508.19, 'low_24h': 7106.6, 'price_change_24h': -199.34722861017053, 'price_change_percentage_24h': -2.65506, 'market_cap_change_24h': -136234971895.33887, 'market_cap_change_percentage_24h': -3.18144, 'circulating_supply': 567838206.9379966, 'total_supply': 620257604.634298, 'max_supply': None, 'ath': 25396, 'ath_change_percentage': -71.22086, 'ath_date': '2025-01-19T11:15:27.957Z', 'atl': 38.03, 'atl_change_percentage': 19120.79484, 'atl_date': '2020-05-11T19:35:23.449Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.650Z'}
{'id': 'tron', 'symbol': 'trx', 'name': 'TRON', 'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193', 'current_price': 25.22, 'market_cap': 2385901622381, 'market_cap_rank': 8, 'fully_diluted_valuation': 2385919872441, 'total_volume': 59067070733, 'high_24h': 25.3, 'low_24h': 24.83, 'price_change_24h': 0.219812, 'price_change_percentage_24h': 0.87929, 'market_cap_change_24h': 16794793781, 'market_cap_change_percentage_24h': 0.70891, 'circulating_supply': 94721007851.9235, 'total_supply': 94721732384.7712, 'max_supply': None, 'ath': 36.53, 'ath_change_percentage': -30.95615, 'ath_date': '2024-12-04T00:10:40.323Z', 'atl': 0.117589, 'atl_change_percentage': 21346.33316, 'atl_date': '2017-11-12T00:00:00.000Z', 'roi': {'times': 145.64231900719585, 'currency': 'usd', 'percentage': 14564.231900719584}, 'last_updated': '2026-02-12T04:16:04.489Z'}
{'id': 'figure-heloc', 'symbol': 'figr_heloc', 'name': 'Figure Heloc', 'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954', 'current_price': 94.55, 'market_cap': 1426133796584, 'market_cap_rank': 9, 'fully_diluted_valuation': 1426133796584, 'total_volume': 4076403880, 'high_24h': 94.79, 'low_24h': 92.87, 'price_change_24h': 1.15, 'price_change_percentage_24h': 1.2305, 'market_cap_change_24h': 18977184917, 'market_cap_change_percentage_24h': 1.34862, 'circulating_supply': 15088846748.267, 'total_supply': 15088846748.267, 'max_supply': None, 'ath': 120.96, 'ath_change_percentage': -21.84998, 'ath_date': '2025-10-28T06:00:43.161Z', 'atl': 13.78, 'atl_change_percentage': 585.77337, 'atl_date': '2025-10-31T14:57:19.271Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.196Z'}
{'id': 'dogecoin', 'symbol': 'doge', 'name': 'Dogecoin', 'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409', 'current_price': 8.33, 'market_cap': 1405111129600, 'market_cap_rank': 10, 'fully_diluted_valuation': 1405402616043, 'total_volume': 101032027769, 'high_24h': 8.4, 'low_24h': 8.02, 'price_change_24h': -0.07010488475473231, 'price_change_percentage_24h': -0.83435, 'market_cap_change_24h': -15437877011.09082, 'market_cap_change_percentage_24h': -1.08675, 'circulating_supply': 168669383126.5791, 'total_supply': 168704373126.579, 'max_supply': None, 'ath': 53.62, 'ath_change_percentage': -84.45984, 'ath_date': '2021-05-08T05:08:23.458Z', 'atl': 0.00552883, 'atl_change_percentage': 150605.92233, 'atl_date': '2015-05-06T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.579Z'}
{'id': 'whitebit', 'symbol': 'wbt', 'name': 'WhiteBIT Coin', 'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096', 'current_price': 4591.21, 'market_cap': 982531224454, 'market_cap_rank': 11, 'fully_diluted_valuation': 1472119321679, 'total_volume': 10929538898, 'high_24h': 4647.34, 'low_24h': 4502.54, 'price_change_24h': -52.89752224252152, 'price_change_percentage_24h': -1.13902, 'market_cap_change_24h': -10914577413.323242, 'market_cap_change_percentage_24h': -1.09866, 'circulating_supply': 213729819.0, 'total_supply': 320229819.0, 'max_supply': 400000000.0, 'ath': 5758.63, 'ath_change_percentage': -20.15135, 'ath_date': '2025-12-10T20:16:13.582Z', 'atl': 245.71, 'atl_change_percentage': 1771.40694, 'atl_date': '2022-09-21T23:38:03.675Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.274Z'}
{'id': 'bitcoin-cash', 'symbol': 'bch', 'name': 'Bitcoin Cash', 'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932', 'current_price': 46591, 'market_cap': 930952639483, 'market_cap_rank': 12, 'fully_diluted_valuation': 930965298699, 'total_volume': 31776290711, 'high_24h': 47453, 'low_24h': 46132, 'price_change_24h': -554.2096908578824, 'price_change_percentage_24h': -1.17553, 'market_cap_change_24h': -12182284394.346191, 'market_cap_change_percentage_24h': -1.29168, 'circulating_supply': 19993556.14665078, 'total_supply': 19993828.02165078, 'max_supply': 21000000.0, 'ath': 242198, 'ath_change_percentage': -80.76314, 'ath_date': '2017-12-20T00:00:00.000Z', 'atl': 5536.54, 'atl_change_percentage': 741.52361, 'atl_date': '2018-12-16T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.517Z'}
{'id': 'usds', 'symbol': 'usds', 'name': 'USDS', 'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683', 'current_price': 90.45, 'market_cap': 873200375718, 'market_cap_rank': 13, 'fully_diluted_valuation': 873200375718, 'total_volume': 8661551501, 'high_24h': 90.8, 'low_24h': 90.37, 'price_change_24h': -0.046008065002538956, 'price_change_percentage_24h': -0.05084, 'market_cap_change_24h': 7679344704, 'market_cap_change_percentage_24h': 0.88725, 'circulating_supply': 9659153059.41872, 'total_supply': 9659153059.41872, 'max_supply': None, 'ath': 92.23, 'ath_change_percentage': -1.97179, 'ath_date': '2026-01-29T16:30:24.390Z', 'atl': 79.67, 'atl_change_percentage': 13.48171, 'atl_date': '2024-10-03T13:19:28.826Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.333Z'}
{'id': 'cardano', 'symbol': 'ada', 'name': 'Cardano', 'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090', 'current_price': 23.43, 'market_cap': 861542860952, 'market_cap_rank': 14, 'fully_diluted_valuation': 1053679975958, 'total_volume': 37590258145, 'high_24h': 23.79, 'low_24h': 22.81, 'price_change_24h': -0.22468547646870718, 'price_change_percentage_24h': -0.94966, 'market_cap_change_24h': -12340330235.120117, 'market_cap_change_percentage_24h': -1.41213, 'circulating_supply': 36794311012.29324, 'total_supply': 45000000000.0, 'max_supply': 45000000000.0, 'ath': 225.26, 'ath_change_percentage': -89.5966, 'ath_date': '2021-09-02T06:00:10.474Z', 'atl': 1.38, 'atl_change_percentage': 1603.84239, 'atl_date': '2017-11-02T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.821Z'}
{'id': 'leo-token', 'symbol': 'leo', 'name': 'LEO Token', 'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607', 'current_price': 762.8, 'market_cap': 702427295602, 'market_cap_rank': 15, 'fully_diluted_valuation': 751108798167, 'total_volume': 158057157, 'high_24h': 768.23, 'low_24h': 739.45, 'price_change_24h': 6.71, 'price_change_percentage_24h': 0.88745, 'market_cap_change_24h': 4522681310, 'market_cap_change_percentage_24h': 0.64804, 'circulating_supply': 921383322.9, 'total_supply': 985239504.0, 'max_supply': None, 'ath': 888.26, 'ath_change_percentage': -14.09385, 'ath_date': '2025-12-01T06:16:28.002Z', 'atl': 56.97, 'atl_change_percentage': 1239.33647, 'atl_date': '2019-12-24T15:14:35.376Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.277Z'}
{'id': 'hyperliquid', 'symbol': 'hype', 'name': 'Hyperliquid', 'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300', 'current_price': 2773.14, 'market_cap': 659946095455, 'market_cap_rank': 16, 'fully_diluted_valuation': 2663960175669, 'total_volume': 30199566842, 'high_24h': 2795.71, 'low_24h': 2579.9, 'price_change_24h': 178.37, 'price_change_percentage_24h': 6.87425, 'market_cap_change_24h': 38860940571, 'market_cap_change_percentage_24h': 6.25694, 'circulating_supply': 238385315.9541414, 'total_supply': 962274028.9541414, 'max_supply': 1000000000.0, 'ath': 5213.52, 'ath_change_percentage': -46.80877, 'ath_date': '2025-09-18T03:30:30.650Z', 'atl': 321.88, 'atl_change_percentage': 761.54569, 'atl_date': '2024-11-29T09:30:30.871Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.297Z'}
{'id': 'monero', 'symbol': 'xmr', 'name': 'Monero', 'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460', 'current_price': 31870, 'market_cap': 583612518850, 'market_cap_rank': 17, 'fully_diluted_valuation': 583612518850, 'total_volume': 7932037724, 'high_24h': 31948, 'low_24h': 30245, 'price_change_24h': 808.56, 'price_change_percentage_24h': 2.60306, 'market_cap_change_24h': 9322844442, 'market_cap_change_percentage_24h': 1.62337, 'circulating_supply': 18446744.07370955, 'total_supply': 18446744.07370955, 'max_supply': None, 'ath': 72026, 'ath_change_percentage': -55.75147, 'ath_date': '2026-01-14T19:34:07.049Z', 'atl': 13.57, 'atl_change_percentage': 234744.03852, 'atl_date': '2015-01-14T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.355Z'}
{'id': 'ethena-usde', 'symbol': 'usde', 'name': 'Ethena USDe', 'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059', 'current_price': 90.4, 'market_cap': 575672477768, 'market_cap_rank': 18, 'fully_diluted_valuation': 575672477768, 'total_volume': 14754076713, 'high_24h': 90.71, 'low_24h': 90.29, 'price_change_24h': 0.00222289, 'price_change_percentage_24h': 0.00246, 'market_cap_change_24h': -5597454563.898071, 'market_cap_change_percentage_24h': -0.96297, 'circulating_supply': 6371643821.691264, 'total_supply': 6371643821.691264, 'max_supply': None, 'ath': 92.91, 'ath_change_percentage': -2.7458, 'ath_date': '2025-12-09T17:10:12.652Z', 'atl': 78.05, 'atl_change_percentage': 15.7817, 'atl_date': '2024-10-04T07:57:15.809Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.410Z'}
{'id': 'canton-network', 'symbol': 'cc', 'name': 'Canton', 'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299', 'current_price': 15.1, 'market_cap': 566295660835, 'market_cap_rank': 19, 'fully_diluted_valuation': 566295660835, 'total_volume': 1263121076, 'high_24h': 15.3, 'low_24h': 14.71, 'price_change_24h': 0.095684, 'price_change_percentage_24h': 0.63762, 'market_cap_change_24h': -540109826.439209, 'market_cap_change_percentage_24h': -0.09529, 'circulating_supply': 37730423662.41153, 'total_supply': 37730423662.41153, 'max_supply': None, 'ath': 17.72, 'ath_change_percentage': -15.39275, 'ath_date': '2026-01-31T16:41:41.560Z', 'atl': 5.31, 'atl_change_percentage': 182.45525, 'atl_date': '2025-12-06T10:32:09.784Z', 'roi': None, 'last_updated': '2026-02-12T04:16:04.370Z'}
{'id': 'chainlink', 'symbol': 'link', 'name': 'Chainlink', 'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405', 'current_price': 762.49, 'market_cap': 539684475036, 'market_cap_rank': 20, 'fully_diluted_valuation': 762158589967, 'total_volume': 37598199071, 'high_24h': 772.19, 'low_24h': 740.26, 'price_change_24h': -7.473779857015984, 'price_change_percentage_24h': -0.97067, 'market_cap_change_24h': -7783866335.832336, 'market_cap_change_percentage_24h': -1.42179, 'circulating_supply': 708099970.4525867, 'total_supply': 1000000000.0, 'max_supply': 1000000000.0, 'ath': 3862.15, 'ath_change_percentage': -80.25742, 'ath_date': '2021-05-10T00:13:57.214Z', 'atl': 9.55, 'atl_change_percentage': 7886.96168, 'atl_date': '2017-11-29T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.722Z'}
{'id': 'usd1-wlfi', 'symbol': 'usd1', 'name': 'USD1', 'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002', 'current_price': 90.43, 'market_cap': 486430640010, 'market_cap_rank': 21, 'fully_diluted_valuation': 486430640010, 'total_volume': 220824195703, 'high_24h': 90.82, 'low_24h': 90.34, 'price_change_24h': -0.0605849002316603, 'price_change_percentage_24h': -0.06695, 'market_cap_change_24h': -406818584.0609131, 'market_cap_change_percentage_24h': -0.08356, 'circulating_supply': 5380664311.030412, 'total_supply': 5380664311.030412, 'max_supply': None, 'ath': 92.17, 'ath_change_percentage': -1.88123, 'ath_date': '2026-01-28T15:56:38.616Z', 'atl': 83.75, 'atl_change_percentage': 7.98155, 'atl_date': '2025-05-02T03:46:49.689Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.826Z'}
{'id': 'stellar', 'symbol': 'xlm', 'name': 'Stellar', 'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350', 'current_price': 14.17, 'market_cap': 463234670464, 'market_cap_rank': 22, 'fully_diluted_valuation': 707754434460, 'total_volume': 9151336836, 'high_24h': 14.26, 'low_24h': 13.7, 'price_change_24h': -0.021558417652073558, 'price_change_percentage_24h': -0.15193, 'market_cap_change_24h': -2336903897.3499146, 'market_cap_change_percentage_24h': -0.50194, 'circulating_supply': 32726833124.45822, 'total_supply': 50001786883.65895, 'max_supply': None, 'ath': 58.01, 'ath_change_percentage': -75.5751, 'ath_date': '2021-05-16T09:48:45.220Z', 'atl': 0.02966141, 'atl_change_percentage': 47666.39853, 'atl_date': '2015-03-05T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.675Z'}
{'id': 'dai', 'symbol': 'dai', 'name': 'Dai', 'image': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996', 'current_price': 90.52, 'market_cap': 378848861601, 'market_cap_rank': 23, 'fully_diluted_valuation': 378848861601, 'total_volume': 8039788570, 'high_24h': 90.84, 'low_24h': 90.42, 'price_change_24h': 0.057664, 'price_change_percentage_24h': 0.06374, 'market_cap_change_24h': -951105081.1895752, 'market_cap_change_percentage_24h': -0.25042, 'circulating_supply': 4189686825.766058, 'total_supply': 4189686825.766058, 'max_supply': None, 'ath': 92.29, 'ath_change_percentage': -1.95873, 'ath_date': '2026-01-31T18:56:20.998Z', 'atl': 64.85, 'atl_change_percentage': 39.5268, 'atl_date': '2019-11-25T00:04:18.137Z', 'roi': None, 'last_updated': '2026-02-12T04:15:52.487Z'}

In [11]:
records=[]  
for i in all_records:
    records.append(dict(ID=i['id'], SYMBOL=i['symbol'], NAME=i['name'], CURRENT_PRICE=i['current_price'], MARKET_CAP=i['market_cap'], 
    MARKET_CAP_RANK=i['market_cap_rank'], TOTAL_VOLUME=i['total_volume'], CIRCULATING_SUPPLY=i['circulating_supply'], TOTAL_SUPPLY=i['total_supply'], 
                   ATH=i['ath'], ATL=i['atl'], LAST_UPDATED=i['last_updated']))

In [12]:
records

[{'ID': 'bitcoin',
  'SYMBOL': 'btc',
  'NAME': 'Bitcoin',
  'CURRENT_PRICE': 6113115,
  'MARKET_CAP': 122071170909890,
  'MARKET_CAP_RANK': 1,
  'TOTAL_VOLUME': 4942894684860,
  'CIRCULATING_SUPPLY': 19987943.0,
  'TOTAL_SUPPLY': 19987943.0,
  'ATH': 11187013,
  'ATL': 3993.42,
  'LAST_UPDATED': '2026-02-12T04:16:00.514Z'},
 {'ID': 'ethereum',
  'SYMBOL': 'eth',
  'NAME': 'Ethereum',
  'CURRENT_PRICE': 178500,
  'MARKET_CAP': 21498509917459,
  'MARKET_CAP_RANK': 2,
  'TOTAL_VOLUME': 2217479903295,
  'CIRCULATING_SUPPLY': 120692542.2815806,
  'TOTAL_SUPPLY': 120692542.2815806,
  'ATH': 431946,
  'ATL': 28.13,
  'LAST_UPDATED': '2026-02-12T04:16:00.872Z'},
 {'ID': 'tether',
  'SYMBOL': 'usdt',
  'NAME': 'Tether',
  'CURRENT_PRICE': 90.46,
  'MARKET_CAP': 16640443292479,
  'MARKET_CAP_RANK': 3,
  'TOTAL_VOLUME': 7806862742638,
  'CIRCULATING_SUPPLY': 184021084709.7995,
  'TOTAL_SUPPLY': 189488021949.4362,
  'ATH': 105.52,
  'ATL': 36.86,
  'LAST_UPDATED': '2026-02-12T04:15:52.939Z'},
 {'ID': 'binancecoin',
  'SYMBOL': 'bnb',
  'NAME': 'BNB',
  'CURRENT_PRICE': 55861,
  'MARKET_CAP': 7614776553122,
  'MARKET_CAP_RANK': 4,
  'TOTAL_VOLUME': 144933998233,
  'CIRCULATING_SUPPLY': 136359446.92,
  'TOTAL_SUPPLY': 136359446.92,
  'ATH': 121422,
  'ATL': 2.58,
  'LAST_UPDATED': '2026-02-12T04:16:00.574Z'},
 {'ID': 'ripple',
  'SYMBOL': 'xrp',
  'NAME': 'XRP',
  'CURRENT_PRICE': 124.65,
  'MARKET_CAP': 7582873135614,
  'MARKET_CAP_RANK': 5,
  'TOTAL_VOLUME': 299852143076,
  'CIRCULATING_SUPPLY': 60917315351.0,
  'TOTAL_SUPPLY': 99985721048.0,
  'ATH': 313.99,
  'ATL': 0.159343,
  'LAST_UPDATED': '2026-02-12T04:15:52.768Z'},
 {'ID': 'usd-coin',
  'SYMBOL': 'usdc',
  'NAME': 'USDC',
  'CURRENT_PRICE': 90.5,
  'MARKET_CAP': 6632385684338,
  'MARKET_CAP_RANK': 6,
  'TOTAL_VOLUME': 525744684430,
  'CIRCULATING_SUPPLY': 73312539559.32837,
  'TOTAL_SUPPLY': 73323588428.17172,
  'ATH': 1327.87,
  'ATL': 65.31,
  'LAST_UPDATED': '2026-02-12T04:15:52.857Z'},
 {'ID': 'solana',
  'SYMBOL': 'sol',
  'NAME': 'Solana',
  'CURRENT_PRICE': 7308.84,
  'MARKET_CAP': 4145950976085,
  'MARKET_CAP_RANK': 7,
  'TOTAL_VOLUME': 409529476338,
  'CIRCULATING_SUPPLY': 567838206.9379966,
  'TOTAL_SUPPLY': 620257604.634298,
  'ATH': 25396,
  'ATL': 38.03,
  'LAST_UPDATED': '2026-02-12T04:15:52.650Z'},
 {'ID': 'tron',
  'SYMBOL': 'trx',
  'NAME': 'TRON',
  'CURRENT_PRICE': 25.22,
  'MARKET_CAP': 2385901622381,
  'MARKET_CAP_RANK': 8,
  'TOTAL_VOLUME': 59067070733,
  'CIRCULATING_SUPPLY': 94721007851.9235,
  'TOTAL_SUPPLY': 94721732384.7712,
  'ATH': 36.53,
  'ATL': 0.117589,
  'LAST_UPDATED': '2026-02-12T04:16:04.489Z'},
 {'ID': 'figure-heloc',
  'SYMBOL': 'figr_heloc',
  'NAME': 'Figure Heloc',
  'CURRENT_PRICE': 94.55,
  'MARKET_CAP': 1426133796584,
  'MARKET_CAP_RANK': 9,
  'TOTAL_VOLUME': 4076403880,
  'CIRCULATING_SUPPLY': 15088846748.267,
  'TOTAL_SUPPLY': 15088846748.267,
  'ATH': 120.96,
  'ATL': 13.78,
  'LAST_UPDATED': '2026-02-12T04:16:04.196Z'},
 {'ID': 'dogecoin',
  'SYMBOL': 'doge',
  'NAME': 'Dogecoin',
  'CURRENT_PRICE': 8.33,
  'MARKET_CAP': 1405111129600,
  'MARKET_CAP_RANK': 10,
  'TOTAL_VOLUME': 101032027769,
  'CIRCULATING_SUPPLY': 168669383126.5791,
  'TOTAL_SUPPLY': 168704373126.579,
  'ATH': 53.62,
  'ATL': 0.00552883,
  'LAST_UPDATED': '2026-02-12T04:16:04.579Z'},
 {'ID': 'whitebit',
  'SYMBOL': 'wbt',
  'NAME': 'WhiteBIT Coin',
  'CURRENT_PRICE': 4591.21,
  'MARKET_CAP': 982531224454,
  'MARKET_CAP_RANK': 11,
  'TOTAL_VOLUME': 10929538898,
  'CIRCULATING_SUPPLY': 213729819.0,
  'TOTAL_SUPPLY': 320229819.0,
  'ATH': 5758.63,
  'ATL': 245.71,
  'LAST_UPDATED': '2026-02-12T04:16:04.274Z'},
 {'ID': 'bitcoin-cash',
  'SYMBOL': 'bch',
  'NAME': 'Bitcoin Cash',
  'CURRENT_PRICE': 46591,
  'MARKET_CAP': 930952639483,
  'MARKET_CAP_RANK': 12,
  'TOTAL_VOLUME': 31776290711,
  'CIRCULATING_SUPPLY': 19993556.14665078,
  'TOTAL_SUPPLY': 19993828.02165078,
  'ATH': 242198,
  'ATL': 5536.54,
  'LAST_UPDATED': '2026-02-12T04:15:52.517Z'},
 {'ID': 'usds',
  'SYMBOL': 'usds',
  'NAME': 'USDS',
  'CURRENT_PRICE': 90.45,
  'MARKET_CAP': 873200375718,
  'MARKET_CAP_RANK': 13,
  'TOTAL_VOLUME': 8661551501,
  'CIRCULATING_SUPPLY': 9659153059.41872,
  'TOTAL_SUPPLY': 9659153059.41872,
  'ATH': 92.23,
  'ATL': 79.67,
  'LAST_UPDATED': '2026-02-12T04:16:04.333Z'},
 {'ID': 'cardano',
  'SYMBOL': 'ada',
  'NAME': 'Cardano',
  'CURRENT_PRICE': 23.43,
  'MARKET_CAP': 861542860952,
  'MARKET_CAP_RANK': 14,
  'TOTAL_VOLUME': 37590258145,
  'CIRCULATING_SUPPLY': 36794311012.29324,
  'TOTAL_SUPPLY': 45000000000.0,
  'ATH': 225.26,
  'ATL': 1.38,
  'LAST_UPDATED': '2026-02-12T04:15:52.821Z'},
 {'ID': 'leo-token',
  'SYMBOL': 'leo',
  'NAME': 'LEO Token',
  'CURRENT_PRICE': 762.8,
  'MARKET_CAP': 702427295602,
  'MARKET_CAP_RANK': 15,
  'TOTAL_VOLUME': 158057157,
  'CIRCULATING_SUPPLY': 921383322.9,
  'TOTAL_SUPPLY': 985239504.0,
  'ATH': 888.26,
  'ATL': 56.97,
  'LAST_UPDATED': '2026-02-12T04:15:52.277Z'},
 {'ID': 'hyperliquid',
  'SYMBOL': 'hype',
  'NAME': 'Hyperliquid',
  'CURRENT_PRICE': 2773.14,
  'MARKET_CAP': 659946095455,
  'MARKET_CAP_RANK': 16,
  'TOTAL_VOLUME': 30199566842,
  'CIRCULATING_SUPPLY': 238385315.9541414,
  'TOTAL_SUPPLY': 962274028.9541414,
  'ATH': 5213.52,
  'ATL': 321.88,
  'LAST_UPDATED': '2026-02-12T04:16:04.297Z'},
 {'ID': 'monero',
  'SYMBOL': 'xmr',
  'NAME': 'Monero',
  'CURRENT_PRICE': 31870,
  'MARKET_CAP': 583612518850,
  'MARKET_CAP_RANK': 17,
  'TOTAL_VOLUME': 7932037724,
  'CIRCULATING_SUPPLY': 18446744.07370955,
  'TOTAL_SUPPLY': 18446744.07370955,
  'ATH': 72026,
  'ATL': 13.57,
  'LAST_UPDATED': '2026-02-12T04:15:52.355Z'},
 {'ID': 'ethena-usde',
  'SYMBOL': 'usde',
  'NAME': 'Ethena USDe',
  'CURRENT_PRICE': 90.4,
  'MARKET_CAP': 575672477768,
  'MARKET_CAP_RANK': 18,
  'TOTAL_VOLUME': 14754076713,
  'CIRCULATING_SUPPLY': 6371643821.691264,
  'TOTAL_SUPPLY': 6371643821.691264,
  'ATH': 92.91,
  'ATL': 78.05,
  'LAST_UPDATED': '2026-02-12T04:15:52.410Z'},
 {'ID': 'canton-network',
  'SYMBOL': 'cc',
  'NAME': 'Canton',
  'CURRENT_PRICE': 15.1,
  'MARKET_CAP': 566295660835,
  'MARKET_CAP_RANK': 19,
  'TOTAL_VOLUME': 1263121076,
  'CIRCULATING_SUPPLY': 37730423662.41153,
  'TOTAL_SUPPLY': 37730423662.41153,
  'ATH': 17.72,
  'ATL': 5.31,
  'LAST_UPDATED': '2026-02-12T04:16:04.370Z'},
 {'ID': 'chainlink',
  'SYMBOL': 'link',
  'NAME': 'Chainlink',
  'CURRENT_PRICE': 762.49,
  'MARKET_CAP': 539684475036,
  'MARKET_CAP_RANK': 20,
  'TOTAL_VOLUME': 37598199071,
  'CIRCULATING_SUPPLY': 708099970.4525867,
  'TOTAL_SUPPLY': 1000000000.0,
  'ATH': 3862.15,
  'ATL': 9.55,
  'LAST_UPDATED': '2026-02-12T04:15:52.722Z'},
 {'ID': 'usd1-wlfi',
  'SYMBOL': 'usd1',
  'NAME': 'USD1',
  'CURRENT_PRICE': 90.43,
  'MARKET_CAP': 486430640010,
  'MARKET_CAP_RANK': 21,
  'TOTAL_VOLUME': 220824195703,
  'CIRCULATING_SUPPLY': 5380664311.030412,
  'TOTAL_SUPPLY': 5380664311.030412,
  'ATH': 92.17,
  'ATL': 83.75,
  'LAST_UPDATED': '2026-02-12T04:15:52.826Z'},
 {'ID': 'stellar',
  'SYMBOL': 'xlm',
  'NAME': 'Stellar',
  'CURRENT_PRICE': 14.17,
  'MARKET_CAP': 463234670464,
  'MARKET_CAP_RANK': 22,
  'TOTAL_VOLUME': 9151336836,
  'CIRCULATING_SUPPLY': 32726833124.45822,
  'TOTAL_SUPPLY': 50001786883.65895,
  'ATH': 58.01,
  'ATL': 0.02966141,
  'LAST_UPDATED': '2026-02-12T04:15:52.675Z'},
 {'ID': 'dai',
  'SYMBOL': 'dai',
  'NAME': 'Dai',
  'CURRENT_PRICE': 90.52,
  'MARKET_CAP': 378848861601,
  'MARKET_CAP_RANK': 23,
  'TOTAL_VOLUME': 8039788570,
  'CIRCULATING_SUPPLY': 4189686825.766058,
  'TOTAL_SUPPLY': 4189686825.766058,
  'ATH': 92.29,
  'ATL': 64.85,
  'LAST_UPDATED': '2026-02-12T04:15:52.487Z'},
 {'ID': 'litecoin',
  'SYMBOL': 'ltc',
  'NAME': 'Litecoin',
  'CURRENT_PRICE': 4781.47,
  'MARKET_CAP': 367074629510,
  'MARKET_CAP_RANK': 24,
  'TOTAL_VOLUME': 29613501450,
  'CIRCULATING_SUPPLY': 76838014.48347135,
  'TOTAL_SUPPLY': 76839545.73347135,
  'ATH': 30082,
  'ATL': 72.12,
  'LAST_UPDATED': '2026-02-12T04:15:52.769Z'},
 {'ID': 'zcash',
  'SYMBOL': 'zec',
  'NAME': 'Zcash',
  'CURRENT_PRICE': 21718,
  'MARKET_CAP': 357912803544,
  'MARKET_CAP_RANK': 25,
  'TOTAL_VOLUME': 39652818238,
  'CIRCULATING_SUPPLY': 16511426.7280448,
  'TOTAL_SUPPLY': 16511426.7280448,
  'ATH': 211171,
  'ATL': 1342.38,
  'LAST_UPDATED': '2026-02-12T04:16:04.569Z'},
 {'ID': 'paypal-usd',
  'SYMBOL': 'pyusd',
  'NAME': 'PayPal USD',
  'CURRENT_PRICE': 90.5,
  'MARKET_CAP': 355195166146,
  'MARKET_CAP_RANK': 26,
  'TOTAL_VOLUME': 29271320165,
  'CIRCULATING_SUPPLY': 3926767507.171984,
  'TOTAL_SUPPLY': 3926767507.171984,
  'ATH': 92.2,
  'ATL': 80.95,
  'LAST_UPDATED': '2026-02-12T04:16:04.512Z'},
 {'ID': 'hedera-hashgraph',
  'SYMBOL': 'hbar',
  'NAME': 'Hedera',
  'CURRENT_PRICE': 8.2,
  'MARKET_CAP': 352409894205,
  'MARKET_CAP_RANK': 27,
  'TOTAL_VOLUME': 8908947929,
  'CIRCULATING_SUPPLY': 43003138665.5085,
  'TOTAL_SUPPLY': 50000000000.0,
  'ATH': 41.81,
  'ATL': 0.703644,
  'LAST_UPDATED': '2026-02-12T04:15:52.474Z'},
 {'ID': 'avalanche-2',
  'SYMBOL': 'avax',
  'NAME': 'Avalanche',
  'CURRENT_PRICE': 791.44,
  'MARKET_CAP': 341550840607,
  'MARKET_CAP_RANK': 28,
  'TOTAL_VOLUME': 26792994641,
  'CIRCULATING_SUPPLY': 431771961.1772119,
  'TOTAL_SUPPLY': 463441061.1772119,
  'ATH': 10772.35,
  'ATL': 204.63,
  'LAST_UPDATED': '2026-02-12T04:16:04.671Z'},
 {'ID': 'shiba-inu',
  'SYMBOL': 'shib',
  'NAME': 'Shiba Inu',
  'CURRENT_PRICE': 0.0005419,
  'MARKET_CAP': 319123386348,
  'MARKET_CAP_RANK': 29,
  'TOTAL_VOLUME': 13967394082,
  'CIRCULATING_SUPPLY': 589243880917864.1,
  'TOTAL_SUPPLY': 589500418093313.5,
  'ATH': 0.00645756,
  'ATL': 4.169e-09,
  'LAST_UPDATED': '2026-02-12T04:15:52.917Z'},
 {'ID': 'sui',
  'SYMBOL': 'sui',
  'NAME': 'Sui',
  'CURRENT_PRICE': 82.48,
  'MARKET_CAP': 317227793884,
  'MARKET_CAP_RANK': 30,
  'TOTAL_VOLUME': 60020637782,
  'CIRCULATING_SUPPLY': 3846172527.429665,
  'TOTAL_SUPPLY': 10000000000.0,
  'ATH': 458.6,
  'ATL': 30.36,
  'LAST_UPDATED': '2026-02-12T04:15:52.704Z'},
 {'ID': 'rain',
  'SYMBOL': 'rain',
  'NAME': 'Rain',
  'CURRENT_PRICE': 0.885924,
  'MARKET_CAP': 300547255288,
  'MARKET_CAP_RANK': 31,
  'TOTAL_VOLUME': 2918482262,
  'CIRCULATING_SUPPLY': 339864816367.0046,
  'TOTAL_SUPPLY': 1149929334720.836,
  'ATH': 0.989197,
  'ATL': 0.196087,
  'LAST_UPDATED': '2026-02-12T04:15:52.375Z'},
 {'ID': 'the-open-network',
  'SYMBOL': 'ton',
  'NAME': 'Toncoin',
  'CURRENT_PRICE': 122.56,
  'MARKET_CAP': 299837611143,
  'MARKET_CAP_RANK': 32,
  'TOTAL_VOLUME': 8360826838,
  'CIRCULATING_SUPPLY': 2448557896.559664,
  'TOTAL_SUPPLY': 5153892548.630753,
  'ATH': 689.6,
  'ATL': 38.25,
  'LAST_UPDATED': '2026-02-12T04:15:53.134Z'},
 {'ID': 'crypto-com-chain',
  'SYMBOL': 'cro',
  'NAME': 'Cronos',
  'CURRENT_PRICE': 6.92,
  'MARKET_CAP': 274817249409,
  'MARKET_CAP_RANK': 33,
  'TOTAL_VOLUME': 1733641657,
  'CIRCULATING_SUPPLY': 39856044128.81203,
  'TOTAL_SUPPLY': 98389338175.27312,
  'ATH': 72.06,
  'ATL': 0.864137,
  'LAST_UPDATED': '2026-02-12T04:15:52.986Z'},
 {'ID': 'world-liberty-financial',
  'SYMBOL': 'wlfi',
  'NAME': 'World Liberty Financial',
  'CURRENT_PRICE': 9.42,
  'MARKET_CAP': 256462698372,
  'MARKET_CAP_RANK': 34,
  'TOTAL_VOLUME': 11171398322,
  'CIRCULATING_SUPPLY': 27243802538.151154,
  'TOTAL_SUPPLY': 100000000000.0,
  'ATH': 29.22,
  'ATL': 8.91,
  'LAST_UPDATED': '2026-02-12T04:15:53.094Z'},
 {'ID': 'tether-gold',
  'SYMBOL': 'xaut',
  'NAME': 'Tether Gold',
  'CURRENT_PRICE': 454694,
  'MARKET_CAP': 236322790373,
  'MARKET_CAP_RANK': 35,
  'TOTAL_VOLUME': 44869457856,
  'CIRCULATING_SUPPLY': 519825.641699,
  'TOTAL_SUPPLY': 712747.089,
  'ATH': 514631,
  'ATL': 108167,
  'LAST_UPDATED': '2026-02-12T04:15:53.025Z'},
 {'ID': 'memecore',
  'SYMBOL': 'm',
  'NAME': 'MemeCore',
  'CURRENT_PRICE': 129.95,
  'MARKET_CAP': 222816110987,
  'MARKET_CAP_RANK': 36,
  'TOTAL_VOLUME': 900287818,
  'CIRCULATING_SUPPLY': 1734724697.78189,
  'TOTAL_SUPPLY': 5334709274.198482,
  'ATH': 260.79,
  'ATL': 4.05,
  'LAST_UPDATED': '2026-02-12T04:15:52.541Z'},
 {'ID': 'pax-gold',
  'SYMBOL': 'paxg',
  'NAME': 'PAX Gold',
  'CURRENT_PRICE': 458253,
  'MARKET_CAP': 210271299793,
  'MARKET_CAP_RANK': 37,
  'TOTAL_VOLUME': 31977023975,
  'CIRCULATING_SUPPLY': 459009.975,
  'TOTAL_SUPPLY': 459009.975,
  'ATH': 516779,
  'ATL': 100361,
  'LAST_UPDATED': '2026-02-12T04:15:53.035Z'},
 {'ID': 'uniswap',
  'SYMBOL': 'uni',
  'NAME': 'Uniswap',
  'CURRENT_PRICE': 313.94,
  'MARKET_CAP': 198990717850,
  'MARKET_CAP_RANK': 38,
  'TOTAL_VOLUME': 94635103439,
  'CIRCULATING_SUPPLY': 633895278.1680214,
  'TOTAL_SUPPLY': 898880420.0366304,
  'ATH': 3333.06,
  'ATL': 75.81,
  'LAST_UPDATED': '2026-02-12T04:15:53.220Z'},
 {'ID': 'polkadot',
  'SYMBOL': 'dot',
  'NAME': 'Polkadot',
  'CURRENT_PRICE': 116.01,
  'MARKET_CAP': 192810331413,
  'MARKET_CAP_RANK': 39,
  'TOTAL_VOLUME': 10116274850,
  'CIRCULATING_SUPPLY': 1664484863.42703,
  'TOTAL_SUPPLY': 1664484863.42703,
  'ATH': 4095.22,
  'ATL': 103.91,
  'LAST_UPDATED': '2026-02-12T04:15:52.870Z'},
 {'ID': 'mantle',
  'SYMBOL': 'mnt',
  'NAME': 'Mantle',
  'CURRENT_PRICE': 56.14,
  'MARKET_CAP': 182771361322,
  'MARKET_CAP_RANK': 40,
  'TOTAL_VOLUME': 3674535375,
  'CIRCULATING_SUPPLY': 3252944055.63684,
  'TOTAL_SUPPLY': 6219316794.889999,
  'ATH': 253.43,
  'ATL': 25.64,
  'LAST_UPDATED': '2026-02-12T04:15:52.914Z'},
 {'ID': 'blackrock-usd-institutional-digital-liquidity-fund',
  'SYMBOL': 'buidl',
  'NAME': 'BlackRock USD Institutional Digital Liquidity Fund',
  'CURRENT_PRICE': 90.49,
  'MARKET_CAP': 166561817170,
  'MARKET_CAP_RANK': 41,
  'TOTAL_VOLUME': None,
  'CIRCULATING_SUPPLY': 1840586251.820448,
  'TOTAL_SUPPLY': 1840586251.820448,
  'ATH': 92.2,
  'ATL': 83.81,
  'LAST_UPDATED': '2026-02-12T04:05:04.219Z'},
 {'ID': 'falcon-finance',
  'SYMBOL': 'usdf',
  'NAME': 'Falcon USD',
  'CURRENT_PRICE': 90.2,
  'MARKET_CAP': 158811162748,
  'MARKET_CAP_RANK': 42,
  'TOTAL_VOLUME': 94965844,
  'CIRCULATING_SUPPLY': 1761459673.866381,
  'TOTAL_SUPPLY': 1761459673.866381,
  'ATH': 92.45,
  'ATL': 80.47,
  'LAST_UPDATED': '2026-02-12T04:15:52.803Z'},
 {'ID': 'aster-2',
  'SYMBOL': 'aster',
  'NAME': 'Aster',
  'CURRENT_PRICE': 62.77,
  'MARKET_CAP': 155270203015,
  'MARKET_CAP_RANK': 43,
  'TOTAL_VOLUME': 33235657025,
  'CIRCULATING_SUPPLY': 2454947754.91,
  'TOTAL_SUPPLY': 7822985112.446448,
  'ATH': 213.7,
  'ATL': 8.76,
  'LAST_UPDATED': '2026-02-12T04:16:04.605Z'},
 {'ID': 'aave',
  'SYMBOL': 'aave',
  'NAME': 'Aave',
  'CURRENT_PRICE': 9864.59,
  'MARKET_CAP': 149725825371,
  'MARKET_CAP_RANK': 44,
  'TOTAL_VOLUME': 38086519073,
  'CIRCULATING_SUPPLY': 15190358.798100796,
  'TOTAL_SUPPLY': 16000000.0,
  'ATH': 48387,
  'ATL': 1933.39,
  'LAST_UPDATED': '2026-02-12T04:15:53.303Z'},
 {'ID': 'bitget-token',
  'SYMBOL': 'bgb',
  'NAME': 'Bitget Token',
  'CURRENT_PRICE': 213.2,
  'MARKET_CAP': 149178349671,
  'MARKET_CAP_RANK': 45,
  'TOTAL_VOLUME': 2706982033,
  'CIRCULATING_SUPPLY': 699992035.9787906,
  'TOTAL_SUPPLY': 916931610.9787906,
  'ATH': 722.65,
  'ATL': 1.081,
  'LAST_UPDATED': '2026-02-12T04:15:52.657Z'},
 {'ID': 'hashnote-usyc',
  'SYMBOL': 'usyc',
  'NAME': 'Circle USYC',
  'CURRENT_PRICE': 101.11,
  'MARKET_CAP': 143218128176,
  'MARKET_CAP_RANK': 46,
  'TOTAL_VOLUME': 4044.32,
  'CIRCULATING_SUPPLY': 1416486972.321503,
  'TOTAL_SUPPLY': 1416486972.321503,
  'ATH': 102.4,
  'ATL': 86.89,
  'LAST_UPDATED': '2026-02-10T05:42:11.457Z'},
 {'ID': 'global-dollar',
  'SYMBOL': 'usdg',
  'NAME': 'Global Dollar',
  'CURRENT_PRICE': 90.5,
  'MARKET_CAP': 142107719393,
  'MARKET_CAP_RANK': 47,
  'TOTAL_VOLUME': 2848650001,
  'CIRCULATING_SUPPLY': 1570903031.444357,
  'TOTAL_SUPPLY': 1570903031.444357,
  'ATH': 143.35,
  'ATL': 76.61,
  'LAST_UPDATED': '2026-02-12T04:15:52.635Z'},
 {'ID': 'okb',
  'SYMBOL': 'okb',
  'NAME': 'OKB',
  'CURRENT_PRICE': 6770.38,
  'MARKET_CAP': 142011994171,
  'MARKET_CAP_RANK': 48,
  'TOTAL_VOLUME': 1946968116,
  'CIRCULATING_SUPPLY': 21000000.0,
  'TOTAL_SUPPLY': 21000000.0,
  'ATH': 22313,
  'ATL': 40.86,
  'LAST_UPDATED': '2026-02-12T04:15:52.687Z'},
 {'ID': 'htx-dao',
  'SYMBOL': 'htx',
  'NAME': 'HTX DAO',
  'CURRENT_PRICE': 0.00015222,
  'MARKET_CAP': 139498386463,
  'MARKET_CAP_RANK': 49,
  'TOTAL_VOLUME': 1263940442,
  'CIRCULATING_SUPPLY': 916533066327098.8,
  'TOTAL_SUPPLY': 916533066327098.8,
  'ATH': 0.00031771,
  'ATL': 6.739e-05,
  'LAST_UPDATED': '2026-02-12T04:15:52.671Z'},
 {'ID': 'pepe',
  'SYMBOL': 'pepe',
  'NAME': 'Pepe',
  'CURRENT_PRICE': 0.00032823,
  'MARKET_CAP': 138095479412,
  'MARKET_CAP_RANK': 50,
  'TOTAL_VOLUME': 31082627083,
  'CIRCULATING_SUPPLY': 420690000000000.0,
  'TOTAL_SUPPLY': 420690000000000.0,
  'ATH': 0.00237833,
  'ATL': 4.52e-06,
  'LAST_UPDATED': '2026-02-12T04:15:53.342Z'},
 {'ID': 'ripple-usd',
  'SYMBOL': 'rlusd',
  'NAME': 'Ripple USD',
  'CURRENT_PRICE': 90.53,
  'MARKET_CAP': 137711137903,
  'MARKET_CAP_RANK': 51,
  'TOTAL_VOLUME': 18405819306,
  'CIRCULATING_SUPPLY': 1521941230.127498,
  'TOTAL_SUPPLY': 1521941230.127498,
  'ATH': 92.15,
  'ATL': 81.72,
  'LAST_UPDATED': '2026-02-12T04:15:52.824Z'},
 {'ID': 'sky',
  'SYMBOL': 'sky',
  'NAME': 'Sky',
  'CURRENT_PRICE': 5.94,
  'MARKET_CAP': 136366409076,
  'MARKET_CAP_RANK': 52,
  'TOTAL_VOLUME': 1733823774,
  'CIRCULATING_SUPPLY': 23011586978.627754,
  'TOTAL_SUPPLY': 23462665147.36596,
  'ATH': 8.62,
  'ATL': 3.12,
  'LAST_UPDATED': '2026-02-12T04:15:53.109Z'},
 {'ID': 'bittensor',
  'SYMBOL': 'tao',
  'NAME': 'Bittensor',
  'CURRENT_PRICE': 13797.72,
  'MARKET_CAP': 132172781855,
  'MARKET_CAP_RANK': 53,
  'TOTAL_VOLUME': 9731179886,
  'CIRCULATING_SUPPLY': 9597491.0,
  'TOTAL_SUPPLY': 21000000.0,
  'ATH': 62722,
  'ATL': 2535.93,
  'LAST_UPDATED': '2026-02-12T04:15:53.210Z'},
 {'ID': 'bfusd',
  'SYMBOL': 'bfusd',
  'NAME': 'BFUSD',
  'CURRENT_PRICE': 90.43,
  'MARKET_CAP': 119324293321,
  'MARKET_CAP_RANK': 54,
  'TOTAL_VOLUME': 907366687,
  'CIRCULATING_SUPPLY': 1320000000.0,
  'TOTAL_SUPPLY': 1320000000.0,
  'ATH': 92.02,
  'ATL': 86.85,
  'LAST_UPDATED': '2026-02-12T04:15:53.086Z'},
 {'ID': 'internet-computer',
  'SYMBOL': 'icp',
  'NAME': 'Internet Computer',
  'CURRENT_PRICE': 213.79,
  'MARKET_CAP': 117012494341,
  'MARKET_CAP_RANK': 55,
  'TOTAL_VOLUME': 4965675097,
  'CIRCULATING_SUPPLY': 548186881.611348,
  'TOTAL_SUPPLY': 548187033.1367216,
  'ATH': 51433,
  'ATL': 187.57,
  'LAST_UPDATED': '2026-02-12T04:15:52.741Z'},
 {'ID': 'ethereum-classic',
  'SYMBOL': 'etc',
  'NAME': 'Ethereum Classic',
  'CURRENT_PRICE': 749.39,
  'MARKET_CAP': 116538640970,
  'MARKET_CAP_RANK': 56,
  'TOTAL_VOLUME': 5656792675,
  'CIRCULATING_SUPPLY': 155496415.7878204,
  'TOTAL_SUPPLY': 155496415.7878204,
  'ATH': 12296.58,
  'ATL': 41.44,
  'LAST_UPDATED': '2026-02-12T04:15:52.694Z'},
 {'ID': 'near',
  'SYMBOL': 'near',
  'NAME': 'NEAR Protocol',
  'CURRENT_PRICE': 88.32,
  'MARKET_CAP': 113586005740,
  'MARKET_CAP_RANK': 57,
  'TOTAL_VOLUME': 14945885799,
  'CIRCULATING_SUPPLY': 1287557465.0,
  'TOTAL_SUPPLY': 1287557499.0,
  'ATH': 1518.16,
  'ATL': 39.17,
  'LAST_UPDATED': '2026-02-12T04:15:52.691Z'},
 {'ID': 'pi-network',
  'SYMBOL': 'pi',
  'NAME': 'Pi Network',
  'CURRENT_PRICE': 12.06,
  'MARKET_CAP': 108647051835,
  'MARKET_CAP_RANK': 58,
  'TOTAL_VOLUME': 1244569271,
  'CIRCULATING_SUPPLY': 9012515463.944277,
  'TOTAL_SUPPLY': 13865408406.06811,
  'ATH': 260.4,
  'ATL': 11.91,
  'LAST_UPDATED': '2026-02-12T04:15:53.148Z'},
 {'ID': 'ondo-finance',
  'SYMBOL': 'ondo',
  'NAME': 'Ondo',
  'CURRENT_PRICE': 22.25,
  'MARKET_CAP': 108322755462,
  'MARKET_CAP_RANK': 59,
  'TOTAL_VOLUME': 5560799109,
  'CIRCULATING_SUPPLY': 4869330647.0,
  'TOTAL_SUPPLY': 10000000000.0,
  'ATH': 181.52,
  'ATL': 6.83,
  'LAST_UPDATED': '2026-02-12T04:15:52.752Z'},
 {'ID': 'gatechain-token',
  'SYMBOL': 'gt',
  'NAME': 'Gate',
  'CURRENT_PRICE': 628.23,
  'MARKET_CAP': 103919175936,
  'MARKET_CAP_RANK': 60,
  'TOTAL_VOLUME': 297613103,
  'CIRCULATING_SUPPLY': 115180573.04885802,
  'TOTAL_SUPPLY': 115180573.04885802,
  'ATH': 2235.58,
  'ATL': 19.44,

In [22]:
import pandas as pd
coins_df=pd.DataFrame(records)
coins_df.head()

,ID,SYMBOL,NAME,CURRENT_PRICE,MARKET_CAP,MARKET_CAP_RANK,TOTAL_VOLUME,CIRCULATING_SUPPLY,TOTAL_SUPPLY,ATH,ATL,LAST_UPDATED
0,bitcoin,btc,Bitcoin,6113115.00,122071170909890,1,4942894684860.00,19987943.00,19987943.00,11187013.00,3993.42,2026-02-12T04:16:00.514Z
1,ethereum,eth,Ethereum,178500.00,21498509917459,2,2217479903295.00,120692542.28,120692542.28,431946.00,28.13,2026-02-12T04:16:00.872Z
2,tether,usdt,Tether,90.46,16640443292479,3,7806862742638.00,184021084709.80,189488021949.44,105.52,36.86,2026-02-12T04:15:52.939Z
3,binancecoin,bnb,BNB,55861.00,7614776553122,4,144933998233.00,136359446.92,136359446.92,121422.00,2.58,2026-02-12T04:16:00.574Z
4,ripple,xrp,XRP,124.65,7582873135614,5,299852143076.00,60917315351.00,99985721048.00,313.99,0.16,2026-02-12T04:15:52.768Z

In [23]:
 
coins_df["LAST_UPDATED"] = pd.to_datetime(coins_df["LAST_UPDATED"]).dt.date

coins_df.head()

,ID,SYMBOL,NAME,CURRENT_PRICE,MARKET_CAP,MARKET_CAP_RANK,TOTAL_VOLUME,CIRCULATING_SUPPLY,TOTAL_SUPPLY,ATH,ATL,LAST_UPDATED
0,bitcoin,btc,Bitcoin,6113115.00,122071170909890,1,4942894684860.00,19987943.00,19987943.00,11187013.00,3993.42,2026-02-12
1,ethereum,eth,Ethereum,178500.00,21498509917459,2,2217479903295.00,120692542.28,120692542.28,431946.00,28.13,2026-02-12
2,tether,usdt,Tether,90.46,16640443292479,3,7806862742638.00,184021084709.80,189488021949.44,105.52,36.86,2026-02-12
3,binancecoin,bnb,BNB,55861.00,7614776553122,4,144933998233.00,136359446.92,136359446.92,121422.00,2.58,2026-02-12
4,ripple,xrp,XRP,124.65,7582873135614,5,299852143076.00,60917315351.00,99985721048.00,313.99,0.16,2026-02-12

In [21]:
df = pd.read_csv("cryptocurrencies_final.csv")
coins_df["LAST_UPDATED"] = pd.to_datetime(coins_df["LAST_UPDATED"]).dt.date
df.to_csv("cryptocurrencies_finish.csv", index=False)

# Top_3_CRYPTOCURRENCIES_Historical_prices

In [ ]:
import requests
import pandas as pd

coin_id = ["tether", "bitcoin", "ethereum"]
all_coins = []

for i in coin_id:
    coin_info_url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
    response = requests.get(coin_info_url)
    coins = response.json()
    
    # Each entry in 'prices' is [timestamp, price]
    coin_df = pd.DataFrame(coins['prices'], columns=['Date', 'Price'])
    coin_df['Coin_id'] = i  # add coin name
    
    # Convert timestamp to date
    coin_df['Date'] = pd.to_datetime(coin_df['Date']).dt.date
    
    # Reorder columns: Coin_id, Date, Price
    coin_df = coin_df[['Coin_id', 'Date', 'Price']]
    all_coins.append(coin_df)
    

# Combine all coins into one DataFrame
final_df = pd.concat(all_coins, ignore_index=True)

# Sample 30 random rows
print(final_df.sample(30))

       Coin_id        Date         Price
5       tether  1970-01-01  8.685007e+01
62      tether  1970-01-01  8.572213e+01
1096  ethereum  1970-01-01  1.759766e+05
485    bitcoin  1970-01-01  9.288883e+06
771   ethereum  1970-01-01  1.720860e+05
1057  ethereum  1970-01-01  2.813889e+05
237     tether  1970-01-01  8.877735e+01
643    bitcoin  1970-01-01  8.373085e+06
915   ethereum  1970-01-01  3.993752e+05
543    bitcoin  1970-01-01  1.023681e+07
872   ethereum  1970-01-01  2.205831e+05
809   ethereum  1970-01-01  1.517070e+05
762   ethereum  1970-01-01  1.661294e+05
67      tether  1970-01-01  8.538152e+01
984   ethereum  1970-01-01  3.335712e+05
60      tether  1970-01-01  8.594840e+01
387    bitcoin  1970-01-01  7.869430e+06
58      tether  1970-01-01  8.604341e+01
770   ethereum  1970-01-01  1.702300e+05
686    bitcoin  1970-01-01  7.835388e+06
189     tether  1970-01-01  8.702531e+01
450    bitcoin  1970-01-01  8.229540e+06
707    bitcoin  1970-01-01  8.414004e+06
661    bitcoin  1970-01-01  8.277612e+06
43      tether  1970-01-01  8.567336e+01
808   ethereum  1970-01-01  1.530459e+05
128     tether  1970-01-01  8.660306e+01
1011  ethereum  1970-01-01  2.760520e+05
1024  ethereum  1970-01-01  2.508299e+05
171     tether  1970-01-01  8.714631e+01

In [2]:
pd.describe_option('display.float_format')

display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]

2. Crypto_prices

In [3]:
#Change Pandas display format
pd.set_option('display.float_format', '{:.2f}'.format)
final_df.sample(10)

      Coin_id        Date       Price
940  ethereum  1970-01-01   379169.38
794  ethereum  1970-01-01   136118.34
914  ethereum  1970-01-01   416582.61
531   bitcoin  1970-01-01 10330494.38
920  ethereum  1970-01-01   354772.70
669   bitcoin  1970-01-01  8175319.49
513   bitcoin  1970-01-01  9541743.48
782  ethereum  1970-01-01   155066.28
996  ethereum  1970-01-01   319468.26
200    tether  1970-01-01       88.19

In [ ]:
final_df.to_csv('coin_price_history.csv', index=False)

3. Oil_prices

In [ ]:
import pandas as pd 
# Load dataset
oil_df=pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

# Convert Date column to datetime
oil_df['Date'] = pd.to_datetime(oil_df['Date'])

# Define start and end dates
start_date = '2020-01-01'
end_date = '2026-01-31'

# Filter rows between those dates
filtered_df = oil_df[(oil_df["Date"] >= start_date) & (oil_df["Date"] <= end_date)]

filtered_df.tail(10)

In [ ]:
filtered_df.to_csv('oil_price_history.csv', index=False)

4. Stock_prices (Yahoo finance API)

In [ ]:
%pip install yfinance

In [ ]:
import yfinance as yf
import pandas as pd

#choose indices
tickers = ['^GSPC', '^DJI', '^IXIC']  # S&P 500, Dow Jones, NASDAQ
start_date = '2020-01-01'
end_date = '2026-01-31'


#download historical data   
stocks_df=yf.download(tickers, start=start_date, end=end_date, group_by='tickers')
stocks_df.head()

In [ ]:
stocks_df1=stocks_df["^GSPC"].reset_index().dropna()

stocks_df1.head()

In [ ]:
stocks_df2=stocks_df["^DJI"].reset_index().dropna()
stocks_df2.head()

In [ ]:
stocks_df3=stocks_df["^IXIC"].reset_index().dropna()
stocks_df3.head()

In [ ]:
#Combine all stocks into one DataFrame
Stocks_prices_df = pd.concat([stocks_df1, stocks_df2, stocks_df3],
    keys=['^GSPC', '^DJI', '^IXIC'],
    names=['Ticker']).reset_index(level='Ticker').dropna()



# Reorder columns
Stocks_prices_df = Stocks_prices_df[['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Ticker']]

Stocks_prices_df = pd.DataFrame(Stocks_prices_df.values,columns=['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Ticker'])

print(Stocks_prices_df.sample(20))

In [ ]:
Stocks_prices_df.to_csv('stocks_price_history.csv', index=False)

In [6]:
import pandas as pd
import mysql.connector
import numpy as np


# 1. Load CSV into Pandas

df=pd.read_csv("cryptocurrencies_finish.csv")   
print("CSV loaded successfully!")
print(df.head())

CSV loaded successfully!
            ID SYMBOL      NAME  CURRENT_PRICE    MARKET_CAP  MARKET_CAP_RANK  \
0      bitcoin    btc   Bitcoin     6322543.00  1.263930e+14                1
1     ethereum    eth  Ethereum      187844.00  2.266600e+13                2
2       tether   usdt    Tether          90.63  1.672470e+13                3
3       ripple    xrp       XRP         131.20  8.001050e+12                4
4  binancecoin    bnb       BNB       57667.00  7.859530e+12                5

   TOTAL_VOLUME  CIRCULATING_SUPPLY  TOTAL_SUPPLY          ATH          ATL  \
0  4.786180e+12        1.998699e+07  1.998699e+07  11187013.00  3993.420000
1  2.230410e+12        1.206926e+08  1.206926e+08    431946.00    28.130000
2  7.723390e+12        1.845180e+11  1.899850e+11       105.52    36.860000
3  3.138200e+11        6.091732e+10  9.998572e+10       313.99     0.159343
4  1.076130e+11        1.363596e+08  1.363596e+08    121422.00     2.580000

  LAST_UPDATED
0   2026-02-10
1   2026-02-10
2   2026-02-10
3   2026-02-10
4   2026-02-10

In [9]:
# 2. Connect to MySQL 

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()
print("Connected to MySQL server successfully!")

Connected to MySQL server successfully!

In [8]:
# 3. Create database if not exists
cursor.execute("CREATE DATABASE IF NOT EXISTS cross_market_analysis_db")
cursor.execute("USE cross_market_analysis_db")

# Create table if not exists
create_table_query = """
CREATE TABLE IF NOT EXISTS cryptocurrencies (
    id VARCHAR(255) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18, 6),       
    market_cap BIGINT,                  
    market_cap_rank INT,                
    total_volume BIGINT,                
    circulating_supply BIGINT,          
    total_supply BIGINT,                
    ath DECIMAL(18, 6),                 
    atl DECIMAL(18, 6),                 
    date DATE                       
)
"""

cursor.execute(create_table_query)


print ("Table created successfully!")

cursor.close()
conn.close()

Table created successfully!

In [10]:

# 4. Push DataFrame into MySQL

# Using executemany (manual control)

insert_query = """
INSERT INTO cryptocurrencies (
    id, symbol, name, current_price, market_cap, market_cap_rank,
    total_volume, circulating_supply, total_supply, ath, atl, date
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

records = df.to_records(index=False)
# Convert DataFrame to native Python types
values = df.replace({np.nan: None}).values.tolist()

# Bulk insert
cursor.executemany(insert_query, values)

conn.commit()
cursor.close()
conn.close()

print("CSV data inserted successfully!")

CSV data inserted successfully!

In [39]:
len(records)

250

In [11]:
import pandas as pd
import mysql.connector
import numpy as np


# 1. Load CSV into Pandas

coin_price_df=pd.read_csv("coin_price_history.csv")   
print("CSV loaded successfully!")
print(coin_price_df.head())

CSV loaded successfully!
  Coin_id                 Date      Price
0  tether  2025-02-11 00:00:00  87.488799
1  tether  2025-02-12 00:00:00  86.772963
2  tether  2025-02-13 00:00:00  86.984129
3  tether  2025-02-14 00:00:00  86.748360
4  tether  2025-02-15 00:00:00  86.673520

In [19]:
# 2. Connect to MySQL 

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()
print("Connected to MySQL server successfully!")

Connected to MySQL server successfully!

In [14]:
# Create table if not exists
cursor.execute("USE cross_market_analysis_db")

create_crypto_coin_prices = """
CREATE TABLE IF NOT EXISTS Crypto_coin_prices (
    coin_id VARCHAR(255),
    date DATE,
    price DECIMAL(20, 8),  
    foreign key (coin_id) references cryptocurrencies(id))
"""


cursor.execute(create_crypto_coin_prices)

print ("Table created successfully!")

cursor.close()
conn.close()

Table created successfully!

In [17]:

# 4. Push DataFrame into MySQL

# Using executemany (manual control)

from datetime import datetime


insert_query = """
INSERT INTO Crypto_coin_prices (coin_id, date, price)
VALUES (%s, %s, %s)
ON DUPLICATE KEY UPDATE price = VALUES(price)
"""


# Convert DataFrame to list of tuples
records = coin_price_df.to_records(index=False)
values = [tuple(record) for record in records]

# Bulk insert
cursor.executemany(insert_query, values)

conn.commit()
cursor.close()
conn.close()

now = datetime.now()
print("Crypto_coin_prices data inserted successfully!")
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

Crypto_coin_prices data inserted successfully!
Timestamp: 2026-02-12 11:31:29

In [21]:
# cursor=conn.cursor()
# select_query = "SELECT * FROM Crypto_coin_prices"
# cursor.execute(select_query)

# # Fetch and print results
# results = cursor.fetchall()
# for row in results:
#     print(row)

# cursor.close()
# conn.close()

In [2]:
import pandas as pd
import mysql.connector
import numpy as np


# 1. Load CSV into Pandas

oil_price_df = pd.read_csv("oil_price_history.csv")   
print("CSV loaded successfully!")
print(oil_price_df.head())

CSV loaded successfully!
        Date      Price
0  4/20/2020  -3,355.49
1  4/21/2020     808.48
2  4/27/2020   1,104.28
3  4/28/2020   1,125.15
4  4/22/2020   1,237.67

In [4]:
# 2. Connect to MySQL 

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()


print("Connected to MySQL server successfully!")

Connected to MySQL server successfully!

In [24]:
#3 .create table if not exists
cursor.execute("USE cross_market_analysis_db")

create_oil_price_history=   """
CREATE TABLE IF NOT EXISTS Oil_prices_history (
    date DATE PRIMARY KEY,              
    price DECIMAL(20, 8)            
);
"""


cursor.execute(create_oil_price_history)


now = datetime.now()
print("Oil_prices_history table created successfully!")
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

cursor.close()
conn.close()

Oil_prices_history table created successfully!
Timestamp: 2026-02-12 11:35:38

In [ ]:
import mysql.connector
from datetime import datetime

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()

cursor.execute("TRUNCATE TABLE Oil_prices_history;")
conn.commit()

now = datetime.now()
print("TRUNCATED TABLE Oil_prices_history;!")
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

In [ ]:
import mysql.connector
from datetime import datetime

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) FROM Oil_prices_history;")
print(cursor.fetchone()[0])

In [10]:
import pandas as pd

# Ensure 'date' column is parsed correctly
oil_price_df['Date'] = pd.to_datetime(oil_price_df['Date'], errors='coerce')

# Format to MySQL-compatible string
oil_price_df['Date'] = oil_price_df['Date'].dt.strftime('%Y-%m-%d')

In [12]:

# 4. Push DataFrame into MySQL


# Fix price format
oil_price_df['Price'] = (
    oil_price_df['Price']
    .astype(str)
    .str.replace(',', '')
    .astype(float)
)

# Insert into MySQL
insert_query = """
INSERT INTO Oil_prices_history (date, price)
VALUES (%s, %s)
"""

records = oil_price_df.to_records(index=False)
values = [tuple(record) for record in records]

cursor.executemany(insert_query, values)
conn.commit()
cursor.close()
conn.close()

In [29]:
import pandas as pd
import mysql.connector
import numpy as np


# 1. Load CSV into Pandas

Stocks_prices_df=pd.read_csv("stocks_price_history.csv")   
print("CSV loaded successfully!")
print(Stocks_prices_df.head())
now=datetime.now()
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

CSV loaded successfully!
         Date     Open     High      Low    Close      Volume Ticker
0  2020-01-02  3244.67  3258.14  3235.53  3257.85  3459930000  ^GSPC
1  2020-01-03  3226.36  3246.15  3222.34  3234.85  3484700000  ^GSPC
2  2020-01-06  3217.55  3246.84  3214.64  3246.28  3702460000  ^GSPC
3  2020-01-07  3241.86  3244.91  3232.43  3237.18  3435910000  ^GSPC
4  2020-01-08  3238.59  3267.07  3236.67  3253.05  3726840000  ^GSPC
Timestamp: 2026-02-12 11:36:43

In [ ]:
# Stocks_prices_df=pd.read_csv("stocks_price_history.csv")
# Stocks_prices_df['Open'] = Stocks_prices_df['Open'].map(lambda x: f"{x:.2f}")
# Stocks_prices_df['Close'] = Stocks_prices_df['Close'].map(lambda x: f"{x:.2f}")
# Stocks_prices_df['High'] = Stocks_prices_df['High'].map(lambda x: f"{x:.2f}")
# Stocks_prices_df['Low'] = Stocks_prices_df['Low'].map(lambda x: f"{x:.2f}")
# Stocks_prices_df
# Stocks_prices_df.to_csv('stocks_price_history.csv', index=False)

In [35]:
# 2. Connect to MySQL 

conn = mysql.connector.connect(
    host="localhost",
    user="root",       
    password="KAvi",
    database="cross_market_analysis_db"
    
    
)
cursor = conn.cursor()
print("Connected to MySQL server successfully!")
now=datetime.now()
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

Connected to MySQL server successfully!
Timestamp: 2026-02-12 11:39:40

In [33]:
# 3. Create table if not exists
cursor.execute("USE cross_market_analysis_db")

create_stock_prices = """
CREATE TABLE IF NOT EXISTS Stock_prices_history (             
    date DATE,
    open DECIMAL(18, 6),
    high DECIMAL(18, 6),
    low DECIMAL(18, 6),
    close DECIMAL(18, 6), 
    volume BIGINT,                              
    ticker VARCHAR(20)              
);
"""

cursor.execute(create_stock_prices)

print("Stock_prices table created successfully!")
now = datetime.now()
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))  
cursor.close()
conn.close()

Stock_prices table created successfully!
Timestamp: 2026-02-12 11:39:19

In [ ]:
# 4. Push DataFrame into MySQL

import mysql.connector
import pandas as pd

# ✅ Convert DataFrame to native Python types and list of lists
values = Stocks_prices_df[['Date','Open','High','Low','Close','Volume','Ticker']].values.tolist()

# Insert query
insert_query = """
INSERT INTO Stock_prices_history (date, open, high, low, close, volume, ticker)
VALUES (%s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    open = VALUES(open),
    high = VALUES(high),
    low = VALUES(low),
    close = VALUES(close),
    volume = VALUES(volume),
    ticker = VALUES(ticker)
"""

# Bulk insert
cursor.executemany(insert_query, values)
conn.commit()

print("Data inserted successfully!")

cursor.close()
conn.close()

Data inserted successfully!

In [39]:
now = datetime.now()
print("Stock_prices_history data inserted successfully!")    
print("Timestamp:", now.strftime("%Y-%m-%d %H:%M:%S"))

Stock_prices_history data inserted successfully!
Timestamp: 2026-02-12 11:41:28